local Phrases = {
	"DA is literally better than IY",
	"hot ui",
	"i cant wait for tohru admin release",
	"give me synapse now",
	"how's life?",
	"if u read this have a good day",
	"ur cool",
	"hey vsauce michael here",
	"hey vsauce michael here, today we are using DA",
	"i have ascended",
	"evolution and the Bible are hurting my brain",
	"where am i?",
	"ur whitelist key is jk there is none lmaooaeofiair",
	"save me from this hell hole called furry land",
	"what",
	"bit.ly/3gV1kmL",
	"i have no oxygen",
	"the backrooms is a great concept for a movie",
	"the americans took our rice again",
	"creeper, aw man, so we back in theaif hqeiorhgierwn",
	"timezones are annoying",
	"every timezone is atleast an hour apart from the ones beside them",
	"what is the meaning to life? the answer is said to be 42. it's based on a movie",
	"heyyyyy",
	"no sharing oki",
	"hey dont trip into the backrooms!",
	"help, i've fallen and i can't get up!",
	"where is my burger?",
	"what is that tall black creature idk probably a spider- AIJJFEI",
	"top 10 famous last words: mlg water bucket into a volcano",
	"EA Sports, copying and pasting games are what they do!",
	"haeden's name in chinese comes out as hayden LOL F",
	"my dad came back after getting milk, took 25 minutes tho",
	"if you read this then how??",
}
return Phrases[math.random(1, #Phrases)]
