local Phrases = {
	"DA is literally better than IY",
	"hot ui",
	"i cant wait for tohru admin release",
	"give me synapse now",
	"how's life?",
	"if u read this have a good day",
	"ur cool",
	"hey vsauce michael here",
	"hey vsauce michael here, today we are using DA",
	"i have ascended",
	"evolution and the Bible are hurting my brain",
	"where am i?",
	"ur whitelist key is jk there is none lmaooaeofiair",
	"save me from this hell hole called furry land",
	"what",
	"bit.ly/3gV1kmL",
	"i have no oxygen",
	"the backrooms is a great concept for a movie",
	"the americans took our rice again",
	"creeper, aw man, so we back in theaif hqeiorhgierwn",
	"timezones are annoying",
	"every timezone is atleast an hour apart from the ones beside them",
	"what is the meaning to life? the answer is said to be 42. it's based on a movie",
	"heyyyyy",
	"no sharing oki",
}
return Phrases[math.random(1, #Phrases)]
