local Phrases = {
	"DA is literally better than IY",
	"hot ui",
	"give me synapse now",
	"how's life?",
	"if u read this have a good day",
	"ur cool",
	"hey vsauce michael here",
	"hey vsauce michael here, today we are using DA",
	"i have ascended",
	"evolution and the Bible are hurting my brain",
	"where am i?",
	"ur whitelist key is jk there is none lmaooaeofiair",
	"save me from this hell hole called furry land",
	"what",
	"bit.ly/3gV1kmL",
	"i have no oxygen",
	"the backrooms is a great concept for a movie",
	"the americans took our rice again",
	"creeper, aw man, so we back in theaif hqeiorhgierwn",
	"timezones are annoying",
	"every timezone is atleast an hour apart from the ones beside them",
	"what is the meaning to life? the answer is said to be 42. it's based on a movie",
	"heyyyyy",
	"no sharing oki",
	"hey dont trip into the backrooms!",
	"help, i've fallen and i can't get up!",
	"where is my burger?",
	"what is that tall black creature idk probably a spider- AIJJFEI",
	"top 10 famous last words: mlg water bucket into a volcano",
	"EA Sports, copying and pasting games are what they do!",
	"haeden's name in chinese comes out as hayden LOL F",
	"my dad came back after getting milk, took 25 minutes tho",
	"if you read this then how??",
	"idk",
	"a narwhal's tusk reveals its past living conditions",
	"\"New car smell\" is the scent of dozens of chemicals",
	"the first person convicted of speeding was going eight miles per hour",
	"the heads on Easter Island have bodies wtf bro",
	"humans are the only animals that blush. wait, did you just say animal?",
	"yo did you know that rabbits can't puke?",
	"the human body literally glows because of protons lmao",
	"dirty or infected door knob? get a copper door knob! they are self-disinfecting",
	"cotton candy was invented by a dentist",
	"chewing gum boosts concentration",
        "to be considered a millionaire nowadays, you need 2.5 million dollars",
	"https://infinite.store.likesyou.org/",
	"among us is a good game, its a murder mystery game, except the memes can be cringe tho",
	"a man survived biting a dorito chip sideways"
}
return tostring(Phrases[math.random(1, #Phrases)])
